/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class AddCarIFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddCarIFrame
     */
    public AddCarIFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModelNameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ManufacturerField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        EngineSizeField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SeatCountField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RegistrationField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RentPerDayField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ColorField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        YearOfManufactureField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        AddButton = new javax.swing.JButton();
        WOFExpiryDatePicker = new org.jdesktop.swingx.JXDatePicker();
        RentedDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel16 = new javax.swing.JLabel();
        ReturnDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel17 = new javax.swing.JLabel();
        FuelTypeField = new javax.swing.JComboBox<>();
        BodyTypeField = new javax.swing.JComboBox<>();
        StatusField = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Add Car");

        ModelNameField.setName(""); // NOI18N
        ModelNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModelNameFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Model Name");

        ManufacturerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManufacturerFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Manufacturer");

        jLabel3.setText("Engine Size");

        jLabel4.setText("Number Of Seats");

        jLabel5.setText("Fuel Type");

        jLabel6.setText("Registration Number");

        jLabel7.setText("WOF Expiry Date");

        jLabel8.setText("Rent per day");

        jLabel9.setText("Color");

        YearOfManufactureField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YearOfManufactureFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("Year of manufacture");

        jLabel11.setText("Status");

        jLabel12.setText("Body Type");

        AddButton.setText("ADD");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        WOFExpiryDatePicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WOFExpiryDatePickerActionPerformed(evt);
            }
        });

        jLabel16.setText("Rented Date");

        jLabel17.setText("Return Date");

        FuelTypeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "petrol", "diesel", "hybrid" }));

        BodyTypeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sedan", "hatchback", "van", "suv" }));

        StatusField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "available", "rented", "repairing" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel2))
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(YearOfManufactureField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ColorField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RentPerDayField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RegistrationField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SeatCountField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EngineSizeField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ManufacturerField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ModelNameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FuelTypeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BodyTypeField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StatusField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(AddButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(WOFExpiryDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RentedDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ReturnDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(AddButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ModelNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ManufacturerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(EngineSizeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(SeatCountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(FuelTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(RegistrationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(RentPerDayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ColorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(YearOfManufactureField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(BodyTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(StatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(WOFExpiryDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ReturnDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RentedDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        String regNo = RegistrationField.getText();
        //Check if registration number is already taken
        if(CarStore.containsCar(regNo))
        {
         JOptionPane.showMessageDialog(this, "Sorry we have a Registration with the number");
        }
        else if(!GUIUtility.emptyInputValidation(this))
        {
            
            //Car model variables
            String modelName = ModelNameField.getText();
            String manufacturer = ManufacturerField.getText();
            double engineSize = Double.parseDouble(EngineSizeField.getText());
            int seatCount = Integer.parseInt(SeatCountField.getText());
            FuelType fuelType = FuelType.valueOf(FuelTypeField.getSelectedItem().toString());
            CarBodyType bodyType = CarBodyType.valueOf(BodyTypeField.getSelectedItem().toString());
            //Car individual variables
            String registrationNumber = RegistrationField.getText();
            Date WOFExpiryDate = WOFExpiryDatePicker.getDate();
            double rentPerDay = Double.parseDouble(RentPerDayField.getText());
            String color = ColorField.getText();
            int yearOfManufacture = Integer.parseInt(YearOfManufactureField.getText());
            ShopStatus shopStatus = ShopStatus.valueOf(StatusField.getSelectedItem().toString());
            Date rentDate = RentedDatePicker.getDate();
            Date returnDate = ReturnDatePicker.getDate();
            //Init car model
            CarModel cm = new CarModel(modelName, manufacturer, engineSize, seatCount, fuelType, bodyType);
            //Init car with previous car model
            Car c = new Car(registrationNumber, WOFExpiryDate, rentPerDay, color, yearOfManufacture, shopStatus, rentDate, returnDate, cm);
            CarStore.cars.add(c);
            JOptionPane.showMessageDialog(this, "Car Added");
            
            //Init current date to fill date pickers with
            Date now = new Date();
            //Reset all fields
            ModelNameField.setText("");
            ManufacturerField.setText("");
            EngineSizeField.setText("");
            SeatCountField.setText("");
            FuelTypeField.setSelectedIndex(0);
            BodyTypeField.setSelectedIndex(0);
            RegistrationField.setText("");
            WOFExpiryDatePicker.setDate(now);
            RentedDatePicker.setDate(now);
            ReturnDatePicker.setDate(now);
            RentPerDayField.setText("");
            ColorField.setText("");
            YearOfManufactureField.setText("");
            StatusField.setSelectedIndex(0);
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void ManufacturerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManufacturerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManufacturerFieldActionPerformed

    private void ModelNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModelNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModelNameFieldActionPerformed

    private void WOFExpiryDatePickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WOFExpiryDatePickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WOFExpiryDatePickerActionPerformed

    private void YearOfManufactureFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YearOfManufactureFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YearOfManufactureFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JComboBox<String> BodyTypeField;
    private javax.swing.JTextField ColorField;
    private javax.swing.JTextField EngineSizeField;
    private javax.swing.JComboBox<String> FuelTypeField;
    private javax.swing.JTextField ManufacturerField;
    private javax.swing.JTextField ModelNameField;
    private javax.swing.JTextField RegistrationField;
    private javax.swing.JTextField RentPerDayField;
    private org.jdesktop.swingx.JXDatePicker RentedDatePicker;
    private org.jdesktop.swingx.JXDatePicker ReturnDatePicker;
    private javax.swing.JTextField SeatCountField;
    private javax.swing.JComboBox<String> StatusField;
    private org.jdesktop.swingx.JXDatePicker WOFExpiryDatePicker;
    private javax.swing.JTextField YearOfManufactureField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
